let arrs = [
    [
        "MÊS",
        "PRODUTO",
        "NÚMERO DE POSTOS PESQUISADOS",
        "UNIDADE DE MEDIDA",
        "PRECO MÉDIO REVENDA",
        "DESVIO PADRÃO REVENDA",
        "PRECO MÍNIMO REVENDA",
        "PRECO MÁXIMO REVENDA",
        "MARGEM MÉDIA REVENDA",
        "COEF DE VARIAÇÃO REVENDA",
        "PRECO MÉDIO DISTRIBUIÇÃO",
        "DESVIO PADRÃO DISTRIBUIÇÃO",
        "PRECO MÍNIMO DISTRIBUIÇÃO",
        "PRECO MÁXIMO DISTRIBUIÇÃO",
        "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
    ],
        [
        "MÊS",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "ESTADO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PRECO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PRECO MÍNIMO REVENDA",
            "PRECO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PRECO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PRECO MÍNIMO DISTRIBUIÇÃO",
            "PRECO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "ESTADO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PRECO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PRECO MÍNIMO REVENDA",
            "PRECO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PRECO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PRECO MÍNIMO DISTRIBUIÇÃO",
            "PRECO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PRECO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PRECO MÍNIMO REVENDA",
            "PRECO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PRECO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PRECO MÍNIMO DISTRIBUIÇÃO",
            "PRECO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "MÊS",
            "PRODUTO",
            "REGIÃO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "ESTADO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "ESTADO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "ESTADO",
            "MUNICÍPIO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ],
        [
        "DATA INICIAL",
            "DATA FINAL",
            "REGIÃO",
            "PRODUTO",
            "NÚMERO DE POSTOS PESQUISADOS",
            "UNIDADE DE MEDIDA",
            "PREÇO MÉDIO REVENDA",
            "DESVIO PADRÃO REVENDA",
            "PREÇO MÍNIMO REVENDA",
            "PREÇO MÁXIMO REVENDA",
            "MARGEM MÉDIA REVENDA",
            "COEF DE VARIAÇÃO REVENDA",
            "PREÇO MÉDIO DISTRIBUIÇÃO",
            "DESVIO PADRÃO DISTRIBUIÇÃO",
            "PREÇO MÍNIMO DISTRIBUIÇÃO",
            "PREÇO MÁXIMO DISTRIBUIÇÃO",
            "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
        ]

]

arrs = arrs.flat(Infinity)

uniq = Array.from(new Set(arrs))

console.log(uniq)